import type { Product, Settings, User } from "./types";

const img = (seed: string, w = 800, h = 800) =>
  `https://picsum.photos/seed/${seed}/${w}/${h}`;

export const defaultUsers: User[] = [
  {
    id: "u_admin",
    name: "Administrador",
    email: "admin@bertolleti.com",
    password: "admin123",
    role: "admin",
    createdAt: new Date().toISOString(),
  },
  {
    id: "u_demo",
    name: "Cliente Demo",
    email: "cliente@bertolleti.com",
    password: "cliente123",
    role: "client",
    createdAt: new Date().toISOString(),
  },
];

export const defaultSettings: Settings = {
  storeName: "Bertolleti Shop",
  storeDescription: "Curadoria premium em produtos para uma vida com mais design.",
  pix_key: "contato@bertolleti.com",
  pix_holder: "Bertolleti Comércio LTDA",
  stripe_public_key: "pk_test_xxxxxxxxxxxx",
  stripe_secret_key: "sk_test_xxxxxxxxxxxx",
  shippingFlat: 24.9,
  freeShippingAbove: 299,
  whatsapp: "(11) 99999-0000",
  email: "contato@bertolleti.com",
};

export const categories = [
  "Tecnologia",
  "Casa",
  "Moda",
  "Acessórios",
  "Escritório",
  "Bem-estar",
];

export const defaultProducts: Product[] = [
  {
    id: "p_001",
    name: "Fone Bluetooth ANC Pro",
    description:
      "Áudio cristalino com cancelamento ativo de ruído, bateria de 40h e drivers de 40mm para uma imersão completa.",
    price: 899.9,
    promo_price: 749.9,
    stock: 24,
    images: [img("fone1"), img("fone2"), img("fone3")],
    category: "Tecnologia",
    sku: "BSH-001",
    active: true,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p_002",
    name: "Luminária de Mesa Minimal",
    description:
      "Design escandinavo, LED regulável em 3 temperaturas e base touch sensitiva.",
    price: 329,
    promo_price: null,
    stock: 12,
    images: [img("lamp1"), img("lamp2")],
    category: "Casa",
    sku: "BSH-002",
    active: true,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p_003",
    name: "Mochila Urban Daypack 22L",
    description: "Tecido impermeável reciclado, compartimento para notebook 16''.",
    price: 459,
    promo_price: 389,
    stock: 8,
    images: [img("bag1"), img("bag2")],
    category: "Acessórios",
    sku: "BSH-003",
    active: true,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p_004",
    name: "Caneca Cerâmica Matte 350ml",
    description: "Acabamento fosco, queima a 1280°C. Resistente à máquina de lavar.",
    price: 79,
    promo_price: null,
    stock: 60,
    images: [img("mug1")],
    category: "Casa",
    sku: "BSH-004",
    active: true,
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p_005",
    name: "Camiseta Pima Essential",
    description: "100% algodão Pima peruano, gramatura 180g, modelagem reta.",
    price: 159,
    promo_price: 129,
    stock: 40,
    images: [img("tee1"), img("tee2")],
    category: "Moda",
    sku: "BSH-005",
    active: true,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p_006",
    name: "Caderno Capa Dura A5",
    description: "192 páginas pontilhadas, papel 90g/m² livre de ácido.",
    price: 89,
    promo_price: null,
    stock: 35,
    images: [img("note1")],
    category: "Escritório",
    sku: "BSH-006",
    active: true,
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p_007",
    name: "Smartwatch Active 2",
    description: "GPS integrado, monitor cardíaco, +30 modos de treino, 14 dias bateria.",
    price: 1299,
    promo_price: 1099,
    stock: 15,
    images: [img("watch1"), img("watch2")],
    category: "Tecnologia",
    sku: "BSH-007",
    active: true,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p_008",
    name: "Difusor Aromaterapia 300ml",
    description: "Ultrassônico silencioso com 7 cores de LED ambiente.",
    price: 219,
    promo_price: null,
    stock: 22,
    images: [img("diff1")],
    category: "Bem-estar",
    sku: "BSH-008",
    active: true,
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p_009",
    name: "Carteira Slim Couro",
    description: "Couro full grain italiano, bloqueio RFID, design ultrafino.",
    price: 199,
    promo_price: 169,
    stock: 30,
    images: [img("wallet1")],
    category: "Acessórios",
    sku: "BSH-009",
    active: true,
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p_010",
    name: "Teclado Mecânico Compact 75%",
    description: "Switches hot-swap, RGB por tecla, ABNT2 com PBT doubleshot.",
    price: 749,
    promo_price: 649,
    stock: 10,
    images: [img("kbd1"), img("kbd2")],
    category: "Tecnologia",
    sku: "BSH-010",
    active: true,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p_011",
    name: "Vaso Cerâmica Orgânico",
    description: "Peça artesanal, cada unidade é única. Capacidade ~2L.",
    price: 189,
    promo_price: null,
    stock: 18,
    images: [img("vase1")],
    category: "Casa",
    sku: "BSH-011",
    active: true,
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p_012",
    name: "Garrafa Térmica 750ml Inox",
    description: "Mantém quente por 12h e gelado por 24h. Aço 18/8.",
    price: 149,
    promo_price: 119,
    stock: 0,
    images: [img("bottle1")],
    category: "Bem-estar",
    sku: "BSH-012",
    active: true,
    featured: false,
    createdAt: new Date().toISOString(),
  },
];
